# --- Self-Refine Task Configuration ---
self_refine_nle_gen: True
# Dataset & Paths for self_refine
self_refine_dataset: QALD10
self_refine_knowledge_graph: wiki
self_refine_data_path: utils/datasets/qald10/qald_10/qald_10.json 
self_refine_base_cache_path: Final_exp_collection/qald10/raw_complete_gpt4o_mini/data_obj_QALD10_wiki_GPT4o-mini_gpt-4o-mini-2024-07-18.pk
self_refine_log_dir: logs
self_refine_results_save_path: eval_results
self_refine_raw_save_path: Final_exp_collection/qald10/gpt4o_mini_self_refine

# --- Self-Refine NL Explanation Configuration (nle_config) ---
self_refine_nle_llm_name: GPT4o-mini
self_refine_nle_model_version:  gpt-4o-mini-2024-07-18
self_refine_nle_temperature: 0.0
self_refine_nle_max_tokens: -1
self_refine_nle_response_format_json: true
self_refine_nle_json_parsable: true
self_refine_nle_max_attempts: 3
self_refine_nle_wait_seconds: 1
self_refine_nle_gen_use_label: true
self_refine_nle_gen_use_question: false
self_refine_nle_gen_use_layout: true
self_refine_nle_gen_use_parsed: true
self_refine_nle_gen_remove_corr: true
self_refine_nle_gen_remove_few_shot: False
self_refine_nle_gen_use_raw_query: false
self_refine_nle_gen_new_NL_exp_prompt: false
self_refine_nle_gen_no_comment_remover: true 
self_refine_refine_query_no_comment_regen: false

# --- Self-Refine Feedback Configuration (feedback_config) ---
self_refine_feedback_llm_name: gpt-4o-2024-08-06
self_refine_feedback_temperature: 0.2

# --- Self-Refine Refine Query Configuration (refine_config) ---
self_refine_refine_query_llm_name: GPT4o-mini
self_refine_refine_query_model_version:  gpt-4o-mini-2024-07-18
self_refine_refine_query_temperature: 0.0
self_refine_refine_query_max_tokens: -1
self_refine_refine_query_response_format_json: false

# --- Self-Refine Pipeline Control ---
self_refine_max_iterations: 5
self_refine_if_ground: false
self_refine_if_nl_exp: false
self_refine_if_external: false
self_refine_debug: false
