# --- Self-Refine Task Configuration ---
self_refine_nle_gen: true
self_refine_dbg: false
# Dataset & Paths for self_refine
self_refine_dataset: QALD9
self_refine_knowledge_graph: wiki
self_refine_data_path: utils/datasets/qald9/qald_9_plus/qald_9_plus_train_wikidata.json
self_refine_base_cache_path: Final_exp_collection/qald9_wiki/raw_complete_claude/data_obj_QALD9_wiki_Claude_claude-3-5-sonnet-20241022.pk
self_refine_log_dir: logs
self_refine_results_save_path: eval_results
self_refine_raw_save_path: Final_exp_collection/qald9_wiki/claude_self_refine

# --- Self-Refine NL Explanation Configuration (nle_config) ---
self_refine_nle_llm_name: Claude
self_refine_nle_model_version: claude-3-5-sonnet-20241022
self_refine_nle_temperature: 0.0
self_refine_nle_max_tokens: 8192
self_refine_nle_response_format_json: true
self_refine_nle_json_parsable: true
self_refine_nle_max_attempts: 3
self_refine_nle_wait_seconds: 1
self_refine_nle_gen_use_label: true
self_refine_nle_gen_use_question: false
self_refine_nle_gen_use_layout: true
self_refine_nle_gen_use_parsed: true
self_refine_nle_gen_remove_corr: true
self_refine_nle_gen_remove_few_shot: False
self_refine_nle_gen_use_raw_query: false
self_refine_nle_gen_new_NL_exp_prompt: false 
self_refine_nle_gen_no_comment_remover: true 
self_refine_refine_query_no_comment_regen: false 

# --- Self-Refine Feedback Configuration (feedback_config) ---
self_refine_feedback_llm_name: gpt-4o-2024-08-06
self_refine_feedback_temperature: 0.2

# --- Self-Refine Refine Query Configuration (refine_config) ---
self_refine_refine_query_llm_name: Claude
self_refine_refine_query_model_version: claude-3-5-sonnet-20241022
self_refine_refine_query_temperature: 0.0
self_refine_refine_query_max_tokens: 8192
self_refine_refine_query_response_format_json: false

# --- Self-Refine Pipeline Control ---
self_refine_max_iterations: 5
self_refine_if_ground: false
self_refine_if_nl_exp: false
self_refine_if_external: false
self_refine_debug: false